version: '3.4'

x-common: &common
  build: .
  volumes:
    - ./djangoplicity:/app/djangoplicity
    - ./test_project/:/app/test_project
    - ./htmlcov:/app/htmlcov
    - ./.coveragerc:/app/.coveragerc

services:
  db:
    image: postgres:10.5
    container_name: djangoplicity-actions-db
    restart: always
    environment:
      POSTGRES_DB: djangoplicity-actions
      POSTGRES_USER: djangoplicity-actions
      POSTGRES_PASSWORD: djangoplicity-actions
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    <<: *common
    container_name: djangoplicity-actions-web-3
    command: ['./scripts/command-dev.sh']
    ports:
      - "8001:8000"
    depends_on:
      - db
  
  
volumes:
  pgdata: