version: '3.4'

x-common: &common
  build: .
  volumes:
    - ./djangoplicity:/app/djangoplicity
    - ./test_project/:/app/test_project
    - ./htmlcov:/app/htmlcov
    - ./.coveragerc:/app/.coveragerc

services:
  db:
    image: postgres:10.5
    container_name: djangoplicity-actions-db
    restart: always
    environment:
      POSTGRES_DB: djangoplicity-actions
      POSTGRES_USER: djangoplicity-actions
      POSTGRES_PASSWORD: djangoplicity-actions
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    <<: *common
    container_name: djangoplicity-actions-web
    command: ['./scripts/command-dev.sh']
    ports:
      - "8001:8000"
    depends_on:
      - db
  
  broker:
    image: rabbitmq:3.8.3
    container_name: djangoplicity-actions-broker
    environment: 
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
  
  celery:
    <<: *common
    container_name: djangoplicity-actions-celery
    command: ["celery", "-B", "--app=test_project", "--hostname=worker1@%h", "--loglevel=INFO", "--queues=celery", "worker"]
    depends_on:
      - broker
      - web
      
volumes:
  pgdata: