version: '3'

services:
  db:
    image: postgres:10.5
    container_name: djangoplicity-actions-db
    restart: always
    environment:
      POSTGRES_DB: djangoplicity-actions
      POSTGRES_USER: djangoplicity-actions
      POSTGRES_PASSWORD: djangoplicity-actions
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: djangoplicity-actions-web
    command: ['./scripts/command-dev.sh']
    volumes:
      - ./djangoplicity:/app/djangoplicity
      - ./test_project/:/app/test_project
      - ./htmlcov:/app/htmlcov
      - ./.coveragerc:/app/.coveragerc
    ports:
      - "8001:8000"
    depends_on:
      - db
volumes:
  pgdata: