# Generated by Django 3.1 on 2022-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='plugin',
            field=models.CharField(choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='type',
            field=models.CharField(choices=[('str', 'Text'), ('int', 'Integer'), ('bool', 'Boolean'), ('date', 'Date')], default='str', max_length=4),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
