# Generated by Django 3.1 on 2020-08-14 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeListTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API key')),
                ('list_id', models.CharField(max_length=50, unique=True)),
                ('web_id', models.CharField(blank=True, max_length=255)),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SomeMergeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.somelisttest')),
            ],
        ),
        migrations.CreateModel(
            name='SomeEventAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_event', models.CharField(choices=[], db_index=True, max_length=50)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('model_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.somelisttest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
